version: '3'

services:
  mongo:
    container_name: cashlog_mongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - cashlog_mongo_volume:/data/mongo
    ports:
      - ${MONGO_PORT:-27017}:27017
    networks:
      - default

  redis:
    container_name: cashlog_redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - default

volumes:
  cashlog_mongo_volume:
